/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.tamarack.creekridge.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.tamarack.creekridge.model.PurchaseOption;
import com.tamarack.creekridge.model.PurchaseOptionModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PurchaseOption service. Represents a row in the &quot;eCreekRidge_PurchaseOption&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.tamarack.creekridge.model.PurchaseOptionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PurchaseOptionImpl}.
 * </p>
 *
 * @author pmacha
 * @see PurchaseOptionImpl
 * @see com.tamarack.creekridge.model.PurchaseOption
 * @see com.tamarack.creekridge.model.PurchaseOptionModel
 * @generated
 */
public class PurchaseOptionModelImpl extends BaseModelImpl<PurchaseOption>
	implements PurchaseOptionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a purchase option model instance should use the {@link com.tamarack.creekridge.model.PurchaseOption} interface instead.
	 */
	public static final String TABLE_NAME = "eCreekRidge_PurchaseOption";
	public static final Object[][] TABLE_COLUMNS = {
			{ "purchaseOptionId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "purchaseOptionName", Types.VARCHAR },
			{ "sequenceNumber", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table eCreekRidge_PurchaseOption (purchaseOptionId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,purchaseOptionName VARCHAR(75) null,sequenceNumber LONG)";
	public static final String TABLE_SQL_DROP = "drop table eCreekRidge_PurchaseOption";
	public static final String ORDER_BY_JPQL = " ORDER BY purchaseOption.sequenceNumber ASC, purchaseOption.purchaseOptionName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY eCreekRidge_PurchaseOption.sequenceNumber ASC, eCreekRidge_PurchaseOption.purchaseOptionName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.tamarack.creekridge.model.PurchaseOption"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.tamarack.creekridge.model.PurchaseOption"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.tamarack.creekridge.model.PurchaseOption"),
			true);
	public static long PURCHASEOPTIONID_COLUMN_BITMASK = 1L;
	public static long PURCHASEOPTIONNAME_COLUMN_BITMASK = 2L;
	public static long SEQUENCENUMBER_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.tamarack.creekridge.model.PurchaseOption"));

	public PurchaseOptionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _purchaseOptionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPurchaseOptionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _purchaseOptionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PurchaseOption.class;
	}

	@Override
	public String getModelClassName() {
		return PurchaseOption.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("purchaseOptionId", getPurchaseOptionId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("purchaseOptionName", getPurchaseOptionName());
		attributes.put("sequenceNumber", getSequenceNumber());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long purchaseOptionId = (Long)attributes.get("purchaseOptionId");

		if (purchaseOptionId != null) {
			setPurchaseOptionId(purchaseOptionId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String purchaseOptionName = (String)attributes.get("purchaseOptionName");

		if (purchaseOptionName != null) {
			setPurchaseOptionName(purchaseOptionName);
		}

		Long sequenceNumber = (Long)attributes.get("sequenceNumber");

		if (sequenceNumber != null) {
			setSequenceNumber(sequenceNumber);
		}
	}

	@Override
	public long getPurchaseOptionId() {
		return _purchaseOptionId;
	}

	@Override
	public void setPurchaseOptionId(long purchaseOptionId) {
		_columnBitmask |= PURCHASEOPTIONID_COLUMN_BITMASK;

		if (!_setOriginalPurchaseOptionId) {
			_setOriginalPurchaseOptionId = true;

			_originalPurchaseOptionId = _purchaseOptionId;
		}

		_purchaseOptionId = purchaseOptionId;
	}

	public long getOriginalPurchaseOptionId() {
		return _originalPurchaseOptionId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getPurchaseOptionName() {
		if (_purchaseOptionName == null) {
			return StringPool.BLANK;
		}
		else {
			return _purchaseOptionName;
		}
	}

	@Override
	public void setPurchaseOptionName(String purchaseOptionName) {
		_columnBitmask = -1L;

		if (_originalPurchaseOptionName == null) {
			_originalPurchaseOptionName = _purchaseOptionName;
		}

		_purchaseOptionName = purchaseOptionName;
	}

	public String getOriginalPurchaseOptionName() {
		return GetterUtil.getString(_originalPurchaseOptionName);
	}

	@Override
	public long getSequenceNumber() {
		return _sequenceNumber;
	}

	@Override
	public void setSequenceNumber(long sequenceNumber) {
		_columnBitmask = -1L;

		_sequenceNumber = sequenceNumber;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			PurchaseOption.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PurchaseOption toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PurchaseOption)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PurchaseOptionImpl purchaseOptionImpl = new PurchaseOptionImpl();

		purchaseOptionImpl.setPurchaseOptionId(getPurchaseOptionId());
		purchaseOptionImpl.setCompanyId(getCompanyId());
		purchaseOptionImpl.setUserId(getUserId());
		purchaseOptionImpl.setUserName(getUserName());
		purchaseOptionImpl.setCreateDate(getCreateDate());
		purchaseOptionImpl.setModifiedDate(getModifiedDate());
		purchaseOptionImpl.setPurchaseOptionName(getPurchaseOptionName());
		purchaseOptionImpl.setSequenceNumber(getSequenceNumber());

		purchaseOptionImpl.resetOriginalValues();

		return purchaseOptionImpl;
	}

	@Override
	public int compareTo(PurchaseOption purchaseOption) {
		int value = 0;

		if (getSequenceNumber() < purchaseOption.getSequenceNumber()) {
			value = -1;
		}
		else if (getSequenceNumber() > purchaseOption.getSequenceNumber()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = getPurchaseOptionName()
					.compareTo(purchaseOption.getPurchaseOptionName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PurchaseOption)) {
			return false;
		}

		PurchaseOption purchaseOption = (PurchaseOption)obj;

		long primaryKey = purchaseOption.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PurchaseOptionModelImpl purchaseOptionModelImpl = this;

		purchaseOptionModelImpl._originalPurchaseOptionId = purchaseOptionModelImpl._purchaseOptionId;

		purchaseOptionModelImpl._setOriginalPurchaseOptionId = false;

		purchaseOptionModelImpl._originalPurchaseOptionName = purchaseOptionModelImpl._purchaseOptionName;

		purchaseOptionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PurchaseOption> toCacheModel() {
		PurchaseOptionCacheModel purchaseOptionCacheModel = new PurchaseOptionCacheModel();

		purchaseOptionCacheModel.purchaseOptionId = getPurchaseOptionId();

		purchaseOptionCacheModel.companyId = getCompanyId();

		purchaseOptionCacheModel.userId = getUserId();

		purchaseOptionCacheModel.userName = getUserName();

		String userName = purchaseOptionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			purchaseOptionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			purchaseOptionCacheModel.createDate = createDate.getTime();
		}
		else {
			purchaseOptionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			purchaseOptionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			purchaseOptionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		purchaseOptionCacheModel.purchaseOptionName = getPurchaseOptionName();

		String purchaseOptionName = purchaseOptionCacheModel.purchaseOptionName;

		if ((purchaseOptionName != null) && (purchaseOptionName.length() == 0)) {
			purchaseOptionCacheModel.purchaseOptionName = null;
		}

		purchaseOptionCacheModel.sequenceNumber = getSequenceNumber();

		return purchaseOptionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{purchaseOptionId=");
		sb.append(getPurchaseOptionId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", purchaseOptionName=");
		sb.append(getPurchaseOptionName());
		sb.append(", sequenceNumber=");
		sb.append(getSequenceNumber());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.tamarack.creekridge.model.PurchaseOption");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>purchaseOptionId</column-name><column-value><![CDATA[");
		sb.append(getPurchaseOptionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>purchaseOptionName</column-name><column-value><![CDATA[");
		sb.append(getPurchaseOptionName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sequenceNumber</column-name><column-value><![CDATA[");
		sb.append(getSequenceNumber());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PurchaseOption.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PurchaseOption.class
		};
	private long _purchaseOptionId;
	private long _originalPurchaseOptionId;
	private boolean _setOriginalPurchaseOptionId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _purchaseOptionName;
	private String _originalPurchaseOptionName;
	private long _sequenceNumber;
	private long _columnBitmask;
	private PurchaseOption _escapedModel;
}