/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.tamarack.creekridge.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.tamarack.creekridge.model.RateFactorRule;
import com.tamarack.creekridge.service.RateFactorRuleLocalServiceUtil;

/**
 * The extended model base implementation for the RateFactorRule service. Represents a row in the &quot;eCreekRidge_RateFactorRule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RateFactorRuleImpl}.
 * </p>
 *
 * @author pmacha
 * @see RateFactorRuleImpl
 * @see com.tamarack.creekridge.model.RateFactorRule
 * @generated
 */
public abstract class RateFactorRuleBaseImpl extends RateFactorRuleModelImpl
	implements RateFactorRule {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rate factor rule model instance should use the {@link RateFactorRule} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			RateFactorRuleLocalServiceUtil.addRateFactorRule(this);
		}
		else {
			RateFactorRuleLocalServiceUtil.updateRateFactorRule(this);
		}
	}
}