/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.tamarack.creekridge.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CreditAppBankReference service. Represents a row in the &quot;eCreekRidge_CreditAppBankReference&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.tamarack.creekridge.model.impl.CreditAppBankReferenceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.tamarack.creekridge.model.impl.CreditAppBankReferenceImpl}.
 * </p>
 *
 * @author pmacha
 * @see CreditAppBankReference
 * @see com.tamarack.creekridge.model.impl.CreditAppBankReferenceImpl
 * @see com.tamarack.creekridge.model.impl.CreditAppBankReferenceModelImpl
 * @generated
 */
public interface CreditAppBankReferenceModel extends AuditedModel,
	BaseModel<CreditAppBankReference> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a credit app bank reference model instance should use the {@link CreditAppBankReference} interface instead.
	 */

	/**
	 * Returns the primary key of this credit app bank reference.
	 *
	 * @return the primary key of this credit app bank reference
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this credit app bank reference.
	 *
	 * @param primaryKey the primary key of this credit app bank reference
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bank reference ID of this credit app bank reference.
	 *
	 * @return the bank reference ID of this credit app bank reference
	 */
	public long getBankReferenceId();

	/**
	 * Sets the bank reference ID of this credit app bank reference.
	 *
	 * @param bankReferenceId the bank reference ID of this credit app bank reference
	 */
	public void setBankReferenceId(long bankReferenceId);

	/**
	 * Returns the company ID of this credit app bank reference.
	 *
	 * @return the company ID of this credit app bank reference
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this credit app bank reference.
	 *
	 * @param companyId the company ID of this credit app bank reference
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this credit app bank reference.
	 *
	 * @return the user ID of this credit app bank reference
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this credit app bank reference.
	 *
	 * @param userId the user ID of this credit app bank reference
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this credit app bank reference.
	 *
	 * @return the user uuid of this credit app bank reference
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this credit app bank reference.
	 *
	 * @param userUuid the user uuid of this credit app bank reference
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this credit app bank reference.
	 *
	 * @return the user name of this credit app bank reference
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this credit app bank reference.
	 *
	 * @param userName the user name of this credit app bank reference
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this credit app bank reference.
	 *
	 * @return the create date of this credit app bank reference
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this credit app bank reference.
	 *
	 * @param createDate the create date of this credit app bank reference
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this credit app bank reference.
	 *
	 * @return the modified date of this credit app bank reference
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this credit app bank reference.
	 *
	 * @param modifiedDate the modified date of this credit app bank reference
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the credit app ID of this credit app bank reference.
	 *
	 * @return the credit app ID of this credit app bank reference
	 */
	public long getCreditAppId();

	/**
	 * Sets the credit app ID of this credit app bank reference.
	 *
	 * @param creditAppId the credit app ID of this credit app bank reference
	 */
	public void setCreditAppId(long creditAppId);

	/**
	 * Returns the sequence number of this credit app bank reference.
	 *
	 * @return the sequence number of this credit app bank reference
	 */
	public long getSequenceNumber();

	/**
	 * Sets the sequence number of this credit app bank reference.
	 *
	 * @param sequenceNumber the sequence number of this credit app bank reference
	 */
	public void setSequenceNumber(long sequenceNumber);

	/**
	 * Returns the bank reference name of this credit app bank reference.
	 *
	 * @return the bank reference name of this credit app bank reference
	 */
	@AutoEscape
	public String getBankReferenceName();

	/**
	 * Sets the bank reference name of this credit app bank reference.
	 *
	 * @param bankReferenceName the bank reference name of this credit app bank reference
	 */
	public void setBankReferenceName(String bankReferenceName);

	/**
	 * Returns the bank reference contact of this credit app bank reference.
	 *
	 * @return the bank reference contact of this credit app bank reference
	 */
	@AutoEscape
	public String getBankReferenceContact();

	/**
	 * Sets the bank reference contact of this credit app bank reference.
	 *
	 * @param bankReferenceContact the bank reference contact of this credit app bank reference
	 */
	public void setBankReferenceContact(String bankReferenceContact);

	/**
	 * Returns the bank reference phone of this credit app bank reference.
	 *
	 * @return the bank reference phone of this credit app bank reference
	 */
	@AutoEscape
	public String getBankReferencePhone();

	/**
	 * Sets the bank reference phone of this credit app bank reference.
	 *
	 * @param bankReferencePhone the bank reference phone of this credit app bank reference
	 */
	public void setBankReferencePhone(String bankReferencePhone);

	/**
	 * Returns the bank referenc account type of this credit app bank reference.
	 *
	 * @return the bank referenc account type of this credit app bank reference
	 */
	@AutoEscape
	public String getBankReferencAccountType();

	/**
	 * Sets the bank referenc account type of this credit app bank reference.
	 *
	 * @param bankReferencAccountType the bank referenc account type of this credit app bank reference
	 */
	public void setBankReferencAccountType(String bankReferencAccountType);

	/**
	 * Returns the bank reference account number of this credit app bank reference.
	 *
	 * @return the bank reference account number of this credit app bank reference
	 */
	@AutoEscape
	public String getBankReferenceAccountNumber();

	/**
	 * Sets the bank reference account number of this credit app bank reference.
	 *
	 * @param bankReferenceAccountNumber the bank reference account number of this credit app bank reference
	 */
	public void setBankReferenceAccountNumber(String bankReferenceAccountNumber);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CreditAppBankReference creditAppBankReference);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CreditAppBankReference> toCacheModel();

	@Override
	public CreditAppBankReference toEscapedModel();

	@Override
	public CreditAppBankReference toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}