/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.tamarack.creekridge.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CreditAppStatus service. Represents a row in the &quot;eCreekRidge_CreditAppStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.tamarack.creekridge.model.impl.CreditAppStatusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.tamarack.creekridge.model.impl.CreditAppStatusImpl}.
 * </p>
 *
 * @author pmacha
 * @see CreditAppStatus
 * @see com.tamarack.creekridge.model.impl.CreditAppStatusImpl
 * @see com.tamarack.creekridge.model.impl.CreditAppStatusModelImpl
 * @generated
 */
public interface CreditAppStatusModel extends AuditedModel,
	BaseModel<CreditAppStatus> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a credit app status model instance should use the {@link CreditAppStatus} interface instead.
	 */

	/**
	 * Returns the primary key of this credit app status.
	 *
	 * @return the primary key of this credit app status
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this credit app status.
	 *
	 * @param primaryKey the primary key of this credit app status
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the credit app status ID of this credit app status.
	 *
	 * @return the credit app status ID of this credit app status
	 */
	public long getCreditAppStatusId();

	/**
	 * Sets the credit app status ID of this credit app status.
	 *
	 * @param CreditAppStatusId the credit app status ID of this credit app status
	 */
	public void setCreditAppStatusId(long CreditAppStatusId);

	/**
	 * Returns the company ID of this credit app status.
	 *
	 * @return the company ID of this credit app status
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this credit app status.
	 *
	 * @param companyId the company ID of this credit app status
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this credit app status.
	 *
	 * @return the user ID of this credit app status
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this credit app status.
	 *
	 * @param userId the user ID of this credit app status
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this credit app status.
	 *
	 * @return the user uuid of this credit app status
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this credit app status.
	 *
	 * @param userUuid the user uuid of this credit app status
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this credit app status.
	 *
	 * @return the user name of this credit app status
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this credit app status.
	 *
	 * @param userName the user name of this credit app status
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this credit app status.
	 *
	 * @return the create date of this credit app status
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this credit app status.
	 *
	 * @param createDate the create date of this credit app status
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this credit app status.
	 *
	 * @return the modified date of this credit app status
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this credit app status.
	 *
	 * @param modifiedDate the modified date of this credit app status
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the credit app status name of this credit app status.
	 *
	 * @return the credit app status name of this credit app status
	 */
	@AutoEscape
	public String getCreditAppStatusName();

	/**
	 * Sets the credit app status name of this credit app status.
	 *
	 * @param creditAppStatusName the credit app status name of this credit app status
	 */
	public void setCreditAppStatusName(String creditAppStatusName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CreditAppStatus creditAppStatus);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CreditAppStatus> toCacheModel();

	@Override
	public CreditAppStatus toEscapedModel();

	@Override
	public CreditAppStatus toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}