/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.tamarack.creekridge.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CreditAppDocument service. Represents a row in the &quot;eCreekRidge_CreditAppDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.tamarack.creekridge.model.impl.CreditAppDocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.tamarack.creekridge.model.impl.CreditAppDocumentImpl}.
 * </p>
 *
 * @author pmacha
 * @see CreditAppDocument
 * @see com.tamarack.creekridge.model.impl.CreditAppDocumentImpl
 * @see com.tamarack.creekridge.model.impl.CreditAppDocumentModelImpl
 * @generated
 */
public interface CreditAppDocumentModel extends AuditedModel,
	BaseModel<CreditAppDocument> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a credit app document model instance should use the {@link CreditAppDocument} interface instead.
	 */

	/**
	 * Returns the primary key of this credit app document.
	 *
	 * @return the primary key of this credit app document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this credit app document.
	 *
	 * @param primaryKey the primary key of this credit app document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the credit app document ID of this credit app document.
	 *
	 * @return the credit app document ID of this credit app document
	 */
	public long getCreditAppDocumentId();

	/**
	 * Sets the credit app document ID of this credit app document.
	 *
	 * @param CreditAppDocumentId the credit app document ID of this credit app document
	 */
	public void setCreditAppDocumentId(long CreditAppDocumentId);

	/**
	 * Returns the company ID of this credit app document.
	 *
	 * @return the company ID of this credit app document
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this credit app document.
	 *
	 * @param companyId the company ID of this credit app document
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this credit app document.
	 *
	 * @return the user ID of this credit app document
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this credit app document.
	 *
	 * @param userId the user ID of this credit app document
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this credit app document.
	 *
	 * @return the user uuid of this credit app document
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this credit app document.
	 *
	 * @param userUuid the user uuid of this credit app document
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this credit app document.
	 *
	 * @return the user name of this credit app document
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this credit app document.
	 *
	 * @param userName the user name of this credit app document
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this credit app document.
	 *
	 * @return the create date of this credit app document
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this credit app document.
	 *
	 * @param createDate the create date of this credit app document
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this credit app document.
	 *
	 * @return the modified date of this credit app document
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this credit app document.
	 *
	 * @param modifiedDate the modified date of this credit app document
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the credit app ID of this credit app document.
	 *
	 * @return the credit app ID of this credit app document
	 */
	public long getCreditAppId();

	/**
	 * Sets the credit app ID of this credit app document.
	 *
	 * @param creditAppId the credit app ID of this credit app document
	 */
	public void setCreditAppId(long creditAppId);

	/**
	 * Returns the sequence number of this credit app document.
	 *
	 * @return the sequence number of this credit app document
	 */
	public long getSequenceNumber();

	/**
	 * Sets the sequence number of this credit app document.
	 *
	 * @param sequenceNumber the sequence number of this credit app document
	 */
	public void setSequenceNumber(long sequenceNumber);

	/**
	 * Returns the document title of this credit app document.
	 *
	 * @return the document title of this credit app document
	 */
	@AutoEscape
	public String getDocumentTitle();

	/**
	 * Sets the document title of this credit app document.
	 *
	 * @param documentTitle the document title of this credit app document
	 */
	public void setDocumentTitle(String documentTitle);

	/**
	 * Returns the document file name of this credit app document.
	 *
	 * @return the document file name of this credit app document
	 */
	@AutoEscape
	public String getDocumentFileName();

	/**
	 * Sets the document file name of this credit app document.
	 *
	 * @param documentFileName the document file name of this credit app document
	 */
	public void setDocumentFileName(String documentFileName);

	/**
	 * Returns the document file location of this credit app document.
	 *
	 * @return the document file location of this credit app document
	 */
	@AutoEscape
	public String getDocumentFileLocation();

	/**
	 * Sets the document file location of this credit app document.
	 *
	 * @param documentFileLocation the document file location of this credit app document
	 */
	public void setDocumentFileLocation(String documentFileLocation);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CreditAppDocument creditAppDocument);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CreditAppDocument> toCacheModel();

	@Override
	public CreditAppDocument toEscapedModel();

	@Override
	public CreditAppDocument toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}