/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.tamarack.creekridge.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PurchaseOption service. Represents a row in the &quot;eCreekRidge_PurchaseOption&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.tamarack.creekridge.model.impl.PurchaseOptionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.tamarack.creekridge.model.impl.PurchaseOptionImpl}.
 * </p>
 *
 * @author pmacha
 * @see PurchaseOption
 * @see com.tamarack.creekridge.model.impl.PurchaseOptionImpl
 * @see com.tamarack.creekridge.model.impl.PurchaseOptionModelImpl
 * @generated
 */
public interface PurchaseOptionModel extends AuditedModel,
	BaseModel<PurchaseOption> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a purchase option model instance should use the {@link PurchaseOption} interface instead.
	 */

	/**
	 * Returns the primary key of this purchase option.
	 *
	 * @return the primary key of this purchase option
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this purchase option.
	 *
	 * @param primaryKey the primary key of this purchase option
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the purchase option ID of this purchase option.
	 *
	 * @return the purchase option ID of this purchase option
	 */
	public long getPurchaseOptionId();

	/**
	 * Sets the purchase option ID of this purchase option.
	 *
	 * @param purchaseOptionId the purchase option ID of this purchase option
	 */
	public void setPurchaseOptionId(long purchaseOptionId);

	/**
	 * Returns the company ID of this purchase option.
	 *
	 * @return the company ID of this purchase option
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this purchase option.
	 *
	 * @param companyId the company ID of this purchase option
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this purchase option.
	 *
	 * @return the user ID of this purchase option
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this purchase option.
	 *
	 * @param userId the user ID of this purchase option
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this purchase option.
	 *
	 * @return the user uuid of this purchase option
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this purchase option.
	 *
	 * @param userUuid the user uuid of this purchase option
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this purchase option.
	 *
	 * @return the user name of this purchase option
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this purchase option.
	 *
	 * @param userName the user name of this purchase option
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this purchase option.
	 *
	 * @return the create date of this purchase option
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this purchase option.
	 *
	 * @param createDate the create date of this purchase option
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this purchase option.
	 *
	 * @return the modified date of this purchase option
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this purchase option.
	 *
	 * @param modifiedDate the modified date of this purchase option
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the purchase option name of this purchase option.
	 *
	 * @return the purchase option name of this purchase option
	 */
	@AutoEscape
	public String getPurchaseOptionName();

	/**
	 * Sets the purchase option name of this purchase option.
	 *
	 * @param purchaseOptionName the purchase option name of this purchase option
	 */
	public void setPurchaseOptionName(String purchaseOptionName);

	/**
	 * Returns the sequence number of this purchase option.
	 *
	 * @return the sequence number of this purchase option
	 */
	public long getSequenceNumber();

	/**
	 * Sets the sequence number of this purchase option.
	 *
	 * @param sequenceNumber the sequence number of this purchase option
	 */
	public void setSequenceNumber(long sequenceNumber);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PurchaseOption purchaseOption);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PurchaseOption> toCacheModel();

	@Override
	public PurchaseOption toEscapedModel();

	@Override
	public PurchaseOption toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}